Rails.application.routes.draw do
  get '/wordofday' => 'jsondata#wordofday'
  get '/jsondata' => 'jsondata#index'
  get '/wordsdetails' => 'jsondata#wordsdetails'
  get '/words/randomWord/api_key:key' => 'jsondata#randomWord'
  get '/words/:word/:action/api_key:key' => 'jsondata#action'
  get '/' => 'users#index'
  get '/+' => 'apigeneration#add'
  get '/X' => 'apigeneration#delete'
  get '/delete' => 'sessions#delete'
  post '/sessions' => 'sessions#create'
  post '/users' => 'users#create'
  get '/jsonpage' =>'jsondata#index'
  get '/dashboard' => 'userpage#index'
  get '/logout' => 'sessions#destroy'
end
